name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'
      - name: Verify vendor
        run: go mod verify
      - name: Build
        run: go build -mod=vendor
      - name: Test with the Go CLI
        run: go test -mod=vendor
